import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <h1 class="cabecalho">Rotas Dinâmicas - Next.js</h1>

      {children}
        <p class="rodape">Todos os direitos reservados. ©️</p>
    </html>
  )
}