import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header class="Cabecalho">
        <h1>Rotas Dinâmicas - Next.js</h1>
      </header>
      {children}
      <footer class="rodape">
        <p>Todos os direitos reservados. ©️</p>
      </footer>
    </html>
  )
}